version: "3"
services: 
  mongo:
    container_name: mongo-container
    image: mongo:3
    restart: always
    ports: 
      - "27017:27017"
  api:
    container_name: api-container
    build: .
    image: clean-node-api
    restart: always
    command: yarn start
    volumes:
      - ./dist:/usr/workspace/clean-node-api/dist
    ports: 
      - "3333:3333"
    links:
      - mongo